export const ALL_CONSONANTS = {
  p: {
    symbol: 'p',
    type: 'Pulmonic Consonants',
    column: 'Bi-labial',
    group: 'Plosives',
  },
  b: {
    symbol: 'b',
    type: 'Pulmonic Consonants',
    column: 'Bi-labial',
    group: 'Plosives',
  },
  d: {
    symbol: 'd',
    type: 'Pulmonic Consonants',
    column: 'Alveolar',
    group: 'Plosives',
  },
  t: {
    symbol: 't',
    type: 'Pulmonic Consonants',
    column: 'Alveolar',
    group: 'Plosives',
  },
  tretro: {
    symbol: 'ʈ',
    type: 'Pulmonic Consonants',
    column: 'Retroflex',
    group: 'Plosives',
  },
  dretro: {
    symbol: 'ɖ',
    type: 'Pulmonic Consonants',
    column: 'Retroflex',
    group: 'Plosives',
  },
  c: {
    symbol: 'c',
    type: 'Pulmonic Consonants',
    column: 'Palatal',
    group: 'Plosives',
  },
  fpal: {
    symbol: 'ɟ',
    type: 'Pulmonic Consonants',
    column: 'Palatal',
    group: 'Plosives',
  },
  k: {
    symbol: 'k',
    type: 'Pulmonic Consonants',
    column: 'Velar',
    group: 'Plosives',
  },
  g: {
    symbol: 'g',
    type: 'Pulmonic Consonants',
    column: 'Velar',
    group: 'Plosives',
  },
  q: {
    symbol: 'q',
    type: 'Pulmonic Consonants',
    column: 'Uvular',
    group: 'Plosives',
  },
  gg: {
    symbol: 'ɢ',
    type: 'Pulmonic Consonants',
    column: 'Uvular',
    group: 'Plosives',
  },
  glottal: {
    symbol: 'ʔ',
    type: 'Pulmonic Consonants',
    column: 'Glottal',
    group: 'Plosives',
  },
  m: {
    symbol: 'm',
    type: 'Pulmonic Consonants',
    column: 'Bi-labial',
    group: 'Nasal',
  },
  mtail: {
    symbol: 'ɱ',
    type: 'Pulmonic Consonants',
    column: 'Labiodental',
    group: 'Nasal',
  },
  n: {
    symbol: 'n',
    type: 'Pulmonic Consonants',
    column: 'Alveolar',
    group: 'Nasal',
  },
  nretro: {
    symbol: 'ɳ',
    type: 'Pulmonic Consonants',
    column: 'Retroflex',
    group: 'Nasal',
  },
  npal: {
    symbol: 'ɲ',
    type: 'Pulmonic Consonants',
    column: 'Palatal',
    group: 'Nasal',
  },
  nn: {
    symbol: 'ŋ',
    type: 'Pulmonic Consonants',
    column: 'Velar',
    group: 'Nasal',
  },
  Nuv: {
    symbol: 'ɴ',
    type: 'Pulmonic Consonants',
    column: 'Uvular',
    group: 'Nasal',
  },
  bb: {
    symbol: 'ʙ',
    type: 'Pulmonic Consonants',
    column: 'Bi-labial',
    group: 'Trill',
  },
  r: {
    symbol: 'r',
    type: 'Pulmonic Consonants',
    column: 'Alveolar',
    group: 'Trill',
  },
  R: {
    symbol: 'ʀ',
    type: 'Pulmonic Consonants',
    column: 'Uvular',
    group: 'Trill',
  },
  rrvl: {
    symbol: 'ɾ',
    type: 'Pulmonic Consonants',
    column: 'Alveolar',
    group: 'Tap / Flap',
  },
  rrvd: {
    symbol: 'ɽ',
    type: 'Pulmonic Consonants',
    column: 'Retroflex',
    group: 'Tap / Flap',
  },
  BlVl: {
    symbol: 'ɸ',
    type: 'Pulmonic Consonants',
    column: 'Bi-labial',
    group: 'Fricative',
  },
  BlVd: {
    symbol: 'β',
    type: 'Pulmonic Consonants',
    column: 'Bi-labial',
    group: 'Fricative',
  },
  f: {
    symbol: 'f',
    type: 'Pulmonic Consonants',
    column: 'Labiodental',
    group: 'Fricative',
  },
  v: {
    symbol: 'v',
    type: 'Pulmonic Consonants',
    column: 'Labiodental',
    group: 'Fricative',
  },
  th: {
    symbol: 'θ',
    type: 'Pulmonic Consonants',
    column: 'Dental',
    group: 'Fricative',
  },
  thvcd: {
    symbol: 'ð',
    type: 'Pulmonic Consonants',
    column: 'Dental',
    group: 'Fricative',
  },
  s: {
    symbol: 's',
    type: 'Pulmonic Consonants',
    column: 'Alveolar',
    group: 'Fricative',
  },
  z: {
    symbol: 'z',
    type: 'Pulmonic Consonants',
    column: 'Alveolar',
    group: 'Fricative',
  },
  ss: {
    symbol: 'ʃ',
    type: 'Pulmonic Consonants',
    column: 'Post-alveolar',
    group: 'Fricative',
  },
  zz: {
    symbol: 'ʒ',
    type: 'Pulmonic Consonants',
    column: 'Post-alveolar',
    group: 'Fricative',
  },
  sretro: {
    symbol: 'ʂ',
    type: 'Pulmonic Consonants',
    column: 'Retroflex',
    group: 'Fricative',
  },
  zretro: {
    symbol: 'ʐ',
    type: 'Pulmonic Consonants',
    column: 'Retroflex',
    group: 'Fricative',
  },
  cpal: {
    symbol: 'ç',
    type: 'Pulmonic Consonants',
    column: 'Palatal',
    group: 'Fricative',
  },
  jpal: {
    symbol: 'ʝ',
    type: 'Pulmonic Consonants',
    column: 'Palatal',
    group: 'Fricative',
  },
  x: {
    symbol: 'x',
    type: 'Pulmonic Consonants',
    column: 'Velar',
    group: 'Fricative',
  },
  yvel: {
    symbol: 'ɣ',
    type: 'Pulmonic Consonants',
    column: 'Velar',
    group: 'Fricative',
  },
  xuv: {
    symbol: 'χ',
    type: 'Pulmonic Consonants',
    column: 'Uvalar',
    group: 'Fricative',
  },
  downR: {
    symbol: 'ʁ',
    type: 'Pulmonic Consonants',
    column: 'Uvalar',
    group: 'Fricative',
  },
  hpha: {
    symbol: 'ħ',
    type: 'Pulmonic Consonants',
    column: 'Pharyngeal',
    group: 'Fricative',
  },
  gpha: {
    symbol: 'ʕ',
    type: 'Pulmonic Consonants',
    column: 'Pharyngeal',
    group: 'Fricative',
  },
  h: {
    symbol: 'h',
    type: 'Pulmonic Consonants',
    column: 'Glottal',
    group: 'Fricative',
  },
  hcurve: {
    symbol: 'ɦ',
    type: 'Pulmonic Consonants',
    column: 'Glottal',
    group: 'Fricative',
  },
  tS: {
    symbol: 'tʃ',
    type: 'Pulmonic Consonants',
    column: 'Post-alveolar',
    group: 'Affricate',
  },
  dZ: {
    symbol: 'dʒ',
    type: 'Pulmonic Consonants',
    column: 'Post-alveolar',
    group: 'Affricate',
  },
  latfone: {
    symbol: 'ɬ',
    type: 'Pulmonic Consonants',
    column: 'Aveolar',
    group: 'Lateral Fricative',
  },
  latftwo: {
    symbol: 'ɮ',
    type: 'Pulmonic Consonants',
    column: 'Aveolar',
    group: 'Lateral Fricative',
  },
  vapprox: {
    symbol: 'ʋ',
    type: 'Pulmonic Consonants',
    column: 'Labiodental',
    group: 'Approximant',
  },
  downr: {
    symbol: 'ɹ',
    type: 'Pulmonic Consonants',
    column: 'Alveolar',
    group: 'Approximant',
  },
  downrretro: {
    symbol: 'ɻ',
    type: 'Pulmonic Consonants',
    column: 'Retroflex',
    group: 'Approximant',
  },
  j: {
    symbol: 'j',
    type: 'Pulmonic Consonants',
    column: 'Palatal',
    group: 'Approximant',
  },
  wvel: {
    symbol: 'ɰ',
    type: 'Pulmonic Consonants',
    column: 'Labio-velar',
    group: 'Approximant',
  },
  l: {
    symbol: 'l',
    type: 'Pulmonic Consonants',
    column: 'Alveolar',
    group: 'Lateral Approximant',
  },
  lretro: {
    symbol: 'ɭ',
    type: 'Pulmonic Consonants',
    column: 'Retroflex',
    group: 'Lateral Approximant',
  },
  ypal: {
    symbol: 'ʎ',
    type: 'Pulmonic Consonants',
    column: 'Palatal',
    group: 'Lateral Approximant',
  },
  lvd: {
    symbol: 'ʟ',
    type: 'Pulmonic Consonants',
    column: 'Velar',
    group: 'Lateral Approximant',
  },
  npcbl: {
    symbol: 'ʘ',
    type: 'Non-Pulmonic Consonants',
    column: 'Clicks',
    group: 'Bilabial',
  },
  npvib: {
    symbol: 'ɓ',
    type: 'Non-Pulmonic Consonants',
    column: 'Voiced Implosives',
    group: 'Bilabial',
  },
  npeb: {
    symbol: 'pʼ',
    type: 'Non-Pulmonic Consonants',
    column: 'Ejectives',
    group: 'Bilabial',
  },
  npcd: {
    symbol: 'ǀ',
    type: 'Non-Pulmonic Consonants',
    column: 'Clicks',
    group: 'Dental',
  },
  npvida: {
    symbol: 'ɗ',
    type: 'Non-Pulmonic Consonants',
    column: 'Voiced Implosives',
    group: 'Dental/alveolar',
  },
  npeda: {
    symbol: 'tʼ',
    type: 'Non-Pulmonic Consonants',
    column: 'Ejectives',
    group: 'Dental/alveolar',
  },
  npcpa: {
    symbol: 'ǃ',
    type: 'Non-Pulmonic Consonants',
    column: 'Clicks',
    group: '(Post)alveoalar',
  },
  npvip: {
    symbol: 'ʄ',
    type: 'Non-Pulmonic Consonants',
    column: 'Voiced Implosives',
    group: 'Palatal',
  },
  npev: {
    symhol: 'kʼ',
    type: 'Non-Pulmonic Consonants',
    column: 'Ejectives',
    group: 'Velar',
  },
  npcpl: {
    symbol: 'ǂ',
    type: 'Non-Pulmonic Consonants',
    column: 'Clicks',
    group: 'Palatoalveolar',
  },
  npviv: {
    symbol: 'ɠ',
    type: 'Non-Pulmonic Consonants',
    column: 'Voiced Implosives',
    group: 'Velar',
  },
  npeaf: {
    symbol: 'sʼ',
    type: 'Non-Pulmonic Consonants',
    column: 'Ejectives',
    group: 'Alveolar fricative',
  },
  npcal: {
    symbol: 'ǁ',
    type: 'Non-Pulmonic Consonants',
    column: 'Clicks',
    group: 'Alveolar lateral',
  },
  npviu: {
    symbol: 'ʛ',
    type: 'Non-Pulmonic Consonants',
    column: 'Voiced Implosives',
    group: 'Uvular',
  },
  ats: {
    symbol: 't͡s',
    type: 'Affricates',
    column: 'Affricates',
    group: 'Voiceless alveolar affricate',
  },
  atsh: {
    symbol: 't͡ʃ',
    type: 'Affricates',
    column: 'Affricates',
    group: 'Voiceless palato-alveolar affricate',
  },
  atc: {
    symbol: 't͡ɕ',
    type: 'Affricates',
    column: 'Affricates',
    group: 'Voiceless alveolo-palatal affricate',
  },
  atS: {
    symbol: 'ʈ͡ʂ',
    type: 'Affricates',
    column: 'Affricates',
    group: 'Voiceless retroflex affricate',
  },
  adz: {
    symbol: 'd͡z',
    type: 'Affricates',
    column: 'Affricates',
    group: 'Voiced alveolar affricate',
  },
  adg: {
    symbol: 'd͡ʒ',
    type: 'Affricates',
    column: 'Affricates',
    group: 'Voiced post-alveolar affricate',
  },
  adzt: {
    symbol: 'd͡ʑ',
    type: 'Affricates',
    column: 'Affricates',
    group: 'Voiced alveolo-palatal affricate',
  },
  adZ: {
    symbol: 'ɖ͡ʐ',
    type: 'Affricates',
    column: 'Affricates',
    group: 'Voiceless retroflex affricate',
  },
  mlva: {
    symbol: 'ʍ',
    type: 'Other',
    column: 'Other Symbols',
    group: 'Voiceless labial-velar fricative',
  },
  w: {
    symbol: 'w',
    type: 'Other',
    column: 'Other Symbols',
    group: 'Voiced labial-velar approximant',
  },
  uoc: {
    symbol: 'ɥ',
    type: 'Other',
    column: 'Other Symbols',
    group: 'Voiced labial-palatal approximant',
  },
  H: {
    symbol: 'ʜ',
    type: 'Other',
    column: 'Other Symbols',
    group: 'Voiceless epiglottal fricative',
  },
  vepi: {
    symbol: 'ʢ',
    type: 'Other',
    column: 'Other Symbols',
    group: 'Voiced epiglottal fricative',
  },
  epip: {
    symbol: 'ʡ',
    type: 'Other',
    column: 'Other Symbols',
    group: 'Epiglottal plosive',
  },
  vapf: {
    symbol: 'ɕ',
    type: 'Other',
    column: 'Other Symbols',
    group: 'Voiceless alveolo-palatal fricative',
  },
  Vapf: {
    symbol: 'ʑ',
    type: 'Other',
    column: 'Other Symbols',
    group: 'Voiced alveolo-palatal fricative',
  },
  ralf: {
    symbol: 'ɺ',
    type: 'Other',
    column: 'Other Symbols',
    group: 'Voiced alveolar lateral flap',
  },
  simul: {
    symbol: 'ɧ',
    type: 'Other',
    column: 'Other Symbols',
    group: 'Simultaneous ʃ and x',
  },
};
